import type { Config } from "tailwindcss";

/**
 * Tailwind theme is a strict override (not extend) — only token-derived classes
 * are allowed. See `KG_DesignSystem_v1.md` Section 7.1 (AI Output Validation Gate).
 *
 * Every colour / spacing / radius / shadow / font value maps to a CSS variable
 * defined in /lib/design/tokens.css (generated by Style Dictionary from
 * /lib/design/tokens.json).
 */
const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    // STRICT OVERRIDE — replaces Tailwind defaults entirely.
    colors: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      brand: {
        red:   "var(--color-brand-red)",
        blue:  "var(--color-brand-blue)",
        white: "var(--color-brand-white)",
      },
      neutral: {
        0:   "var(--color-neutral-0)",
        50:  "var(--color-neutral-50)",
        100: "var(--color-neutral-100)",
        200: "var(--color-neutral-200)",
        400: "var(--color-neutral-400)",
        500: "var(--color-neutral-500)",
        700: "var(--color-neutral-700)",
        900: "var(--color-neutral-900)",
      },
      state: {
        success: "var(--color-state-success)",
        warning: "var(--color-state-warning)",
        error:   "var(--color-state-error)",
        info:    "var(--color-state-info)",
      },
      surface: {
        page:             "var(--color-surface-page)",
        card:             "var(--color-surface-card)",
        "card-elevated":  "var(--color-surface-card-elevated)",
        input:            "var(--color-surface-input)",
        "input-disabled": "var(--color-surface-input-disabled)",
      },
      text: {
        primary:   "var(--color-text-primary)",
        secondary: "var(--color-text-secondary)",
        muted:     "var(--color-text-muted)",
        disabled:  "var(--color-text-disabled)",
        inverse:   "var(--color-text-inverse)",
      },
      border: {
        DEFAULT: "var(--color-border-default)",
        subtle:  "var(--color-border-subtle)",
        focus:   "var(--color-border-focus)",
        error:   "var(--color-border-error)",
      },
    },
    spacing: {
      0:  "var(--spacing-0)",
      1:  "var(--spacing-1)",
      2:  "var(--spacing-2)",
      3:  "var(--spacing-3)",
      4:  "var(--spacing-4)",
      6:  "var(--spacing-6)",
      8:  "var(--spacing-8)",
      12: "var(--spacing-12)",
      16: "var(--spacing-16)",
      24: "var(--spacing-24)",
    },
    borderRadius: {
      none: "0px",
      sm:   "var(--radius-sm)",
      md:   "var(--radius-md)",
      lg:   "var(--radius-lg)",
      xl:   "var(--radius-xl)",
      full: "var(--radius-full)",
    },
    boxShadow: {
      none: "none",
      sm:   "var(--shadow-sm)",
      md:   "var(--shadow-md)",
      lg:   "var(--shadow-lg)",
    },
    fontSize: {
      xs:   "var(--typography-size-xs)",
      sm:   "var(--typography-size-sm)",
      base: "var(--typography-size-base)",
      lg:   "var(--typography-size-lg)",
      xl:   "var(--typography-size-xl)",
      "2xl": "var(--typography-size-2xl)",
      "3xl": "var(--typography-size-3xl)",
      "4xl": "var(--typography-size-4xl)",
    },
    fontFamily: {
      sans: ["var(--typography-family-sans)"],
    },
    fontWeight: {
      regular:  "var(--typography-weight-regular)",
      medium:   "var(--typography-weight-medium)",
      semibold: "var(--typography-weight-semibold)",
      bold:     "var(--typography-weight-bold)",
    },
    lineHeight: {
      tight:   "var(--typography-line-height-tight)",
      snug:    "var(--typography-line-height-snug)",
      normal:  "var(--typography-line-height-normal)",
      relaxed: "var(--typography-line-height-relaxed)",
    },
    screens: {
      sm:   "640px",
      md:   "768px",
      lg:   "1024px",
      xl:   "1280px",
      "2xl": "1536px",
    },
    zIndex: {
      base:     "0",
      elevated: "10",
      sticky:   "20",
      drawer:   "40",
      dialog:   "50",
      toast:    "60",
      tooltip:  "70",
    },
    transitionDuration: {
      fast: "var(--motion-duration-fast)",
      base: "var(--motion-duration-base)",
      slow: "var(--motion-duration-slow)",
    },
    transitionTimingFunction: {
      enter:   "var(--motion-easing-enter)",
      exit:    "var(--motion-easing-exit)",
      default: "var(--motion-easing-default)",
    },
    extend: {},
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
