/**
 * Do not edit directly, this file was auto-generated.
 */

export const ColorBrandRed = "#ef3340"; // PAP red (Pantone 032 approx.). Symbol of action. CTAs, focus rings, primary buttons. Approximate — confirm exact PAP red with HQ before public-facing launch.
export const ColorBrandBlue = "#0052a1"; // PAP blue. Symbol of unity of all races. Secondary CTAs, links, navigation indicators.
export const ColorBrandWhite = "#ffffff"; // PAP white. Symbol of purity + integrity. Dominant surface — card backgrounds, dialog surfaces.
export const ColorNeutral0 = "#ffffff"; // Pure white. Card surfaces, dialog backgrounds.
export const ColorNeutral50 = "#fafafa"; // Page background light grey.
export const ColorNeutral100 = "#f4f4f5"; // Subtle row stripes, hover backgrounds.
export const ColorNeutral200 = "#e4e4e7"; // Borders, dividers, disabled fills.
export const ColorNeutral400 = "#a1a1aa"; // Placeholder text, disabled text.
export const ColorNeutral500 = "#71717a"; // Secondary text, helper text, captions.
export const ColorNeutral700 = "#3f3f46"; // Body text.
export const ColorNeutral900 = "#18181b"; // Headings, primary text, max contrast.
export const ColorStateSuccess = "#16a34a"; // Success badges, completion confirmations.
export const ColorStateWarning = "#f59e0b"; // Warning badges, attention required (amber chase indicator 7–14d).
export const ColorStateError = "#dc2626"; // Error states, rejection badges, red chase indicator >14d.
export const ColorStateInfo = "#2563eb"; // Info banners, neutral notifications.
export const ColorSurfacePage = "#fafafa"; // Page background.
export const ColorSurfaceCard = "#ffffff"; // Card / container background.
export const ColorSurfaceCardElevated = "#ffffff"; // Elevated card (with shadow.md).
export const ColorSurfaceInput = "#ffffff"; // Form input background.
export const ColorSurfaceInputDisabled = "#f4f4f5"; // Disabled input.
export const ColorTextPrimary = "#18181b"; // Headings, body. AA contrast on surface.page.
export const ColorTextSecondary = "#3f3f46"; // Body secondary. AA contrast.
export const ColorTextMuted = "#71717a"; // Helper text. AA contrast 4.5:1.
export const ColorTextDisabled = "#a1a1aa"; // Disabled labels. Not interactive.
export const ColorTextInverse = "#ffffff"; // Text on brand.red background.
export const ColorBorderDefault = "#e4e4e7";
export const ColorBorderSubtle = "#f4f4f5";
export const ColorBorderFocus = "#ef3340"; // Focus ring colour — PAP red for visibility + brand consistency.
export const ColorBorderError = "#dc2626";
export const Spacing0 = "0px";
export const Spacing1 = "4px";
export const Spacing2 = "8px";
export const Spacing3 = "12px";
export const Spacing4 = "16px";
export const Spacing5 = "20px";
export const Spacing6 = "24px";
export const Spacing8 = "32px";
export const Spacing10 = "40px";
export const Spacing12 = "48px";
export const Spacing16 = "64px";
export const Spacing24 = "96px";
export const RadiusSm = "4px";
export const RadiusMd = "8px";
export const RadiusLg = "12px";
export const RadiusXl = "16px";
export const RadiusFull = "9999px";
export const TypographyFamilySans =
  "Inter, system-ui, -apple-system, BlinkMacSystemFont, sans-serif"; // Single typeface for entire system. No serifs Phase 1.
export const TypographyWeightRegular = 400;
export const TypographyWeightMedium = 500;
export const TypographyWeightSemibold = 600;
export const TypographyWeightBold = 700;
export const TypographySizeXs = "12px"; // Caption, legal.
export const TypographySizeSm = "14px"; // Secondary text, dense tables.
export const TypographySizeBase = "16px"; // Body. Minimum for mobile inputs (prevents iOS Safari zoom-on-focus).
export const TypographySizeLg = "18px"; // Lead, large body.
export const TypographySizeXl = "20px"; // Subheadings.
export const TypographySize2xl = "24px"; // Section headings.
export const TypographySize3xl = "30px"; // Page titles.
export const TypographySize4xl = "36px"; // Landing headlines.
export const TypographyLineHeightTight = 1.2;
export const TypographyLineHeightSnug = 1.4;
export const TypographyLineHeightNormal = 1.5;
export const TypographyLineHeightRelaxed = 1.6;
export const ShadowSm = "0 1px 2px 0 rgba(0,0,0,0.05)";
export const ShadowMd = "0 4px 6px -1px rgba(0,0,0,0.07)";
export const ShadowLg = "0 10px 15px -3px rgba(0,0,0,0.10)";
export const BreakpointSm = "640px";
export const BreakpointMd = "768px";
export const BreakpointLg = "1024px";
export const BreakpointXl = "1280px";
export const Breakpoint2xl = "1536px";
export const MotionDurationFast = "150ms"; // Form field state changes, focus ring.
export const MotionDurationBase = "200ms"; // Dialog open, toast slide, dropdown reveal.
export const MotionDurationSlow = "300ms"; // Page transitions, drawer slide.
export const MotionEasingEnter = "cubic-bezier(0, 0, 0.2, 1)"; // Decelerating ease — for incoming elements.
export const MotionEasingExit = "cubic-bezier(0.4, 0, 1, 1)"; // Accelerating ease — for outgoing elements.
export const MotionEasingDefault = "cubic-bezier(0.16, 1, 0.3, 1)"; // Smooth standard ease.
export const ZIndexBase = 0;
export const ZIndexElevated = 10; // Cards, dropdowns inline
export const ZIndexSticky = 20; // Sticky headers, sidebars
export const ZIndexDrawer = 40; // Mobile drawer / sheet
export const ZIndexDialog = 50; // Modal dialogs
export const ZIndexToast = 60; // Toast/Sonner notifications
export const ZIndexTooltip = 70; // Tooltips, hover popovers
