-- =========================================================================
-- Multi-profile model refactor — one user can hold multiple roles at multiple
-- branches simultaneously.
--
-- Trigger: Sebastian needed to be wing_admin of "Young PAP" AND branch_admin
-- of "KG" with the same auth account. Old 1:1 model (profiles.id was both
-- PK and FK to auth.users.id) made this impossible. New model: profiles.id
-- is an independent UUID identity; profiles.user_id is the FK to auth.users.
-- A user can have N profile rows.
--
-- RLS posture: PERMISSIVE — RLS grants access if the user has ANY active
-- profile satisfying the policy, regardless of which workspace they're
-- "in" UI-side. The active-profile cookie is a UX affordance, not a
-- security boundary. Match Slack/Notion/GitHub multi-workspace semantics.
--
-- All existing storage policies use the SECURITY DEFINER helpers
-- (is_branch_user / is_branch_admin_team / is_taylab_staff). Rewriting
-- those helpers auto-updates storage RLS. No storage DDL needed.
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1) Schema: profiles.id becomes independent UUID; new profiles.user_id FK
-- -------------------------------------------------------------------------

-- Add user_id column (nullable for now so we can backfill).
alter table public.profiles add column user_id uuid;

-- Backfill: every existing row's user_id is its current id (since id was FK
-- to auth.users.id under the old 1:1 model).
update public.profiles set user_id = id where user_id is null;

-- Make user_id NOT NULL with FK to auth.users. Cascade delete so removing
-- an auth user wipes all their profiles cleanly.
alter table public.profiles alter column user_id set not null;
alter table public.profiles
  add constraint profiles_user_id_fkey
  foreign key (user_id) references auth.users(id) on delete cascade;

-- Drop the existing id → auth.users FK. profiles.id is now an independent
-- identity (per-profile, not per-user). Existing values stay (they're already
-- valid UUIDs because they came from auth.users.id).
alter table public.profiles drop constraint profiles_id_fkey;

-- New rows generated by the multi-profile branch-creation flow need a UUID
-- default. Existing rows keep their inherited values.
alter table public.profiles alter column id set default gen_random_uuid();

-- One active profile per (user, branch) pair. Partial — only enforced for
-- active rows so deactivated profiles don't block re-invites. NULL branch_id
-- (taylab_staff) gets its own index so a user can only have one active
-- taylab_staff profile.
create unique index profiles_user_branch_unique_active
  on public.profiles (user_id, branch_id)
  where branch_id is not null and is_active = true;

create unique index profiles_user_taylab_unique_active
  on public.profiles (user_id)
  where branch_id is null and is_active = true;

-- Hot lookup path: getAuthContext loads all active profiles for a user.
create index idx_profiles_user_id_active
  on public.profiles (user_id)
  where is_active = true;

-- -------------------------------------------------------------------------
-- 2) Rewrite SECURITY DEFINER helpers — match on user_id, not id
-- -------------------------------------------------------------------------
-- All policies that call these helpers (branches, applications, nric_uploads,
-- signatures, magic_links, link_deliveries, application_events, nudge_log,
-- generated_pdfs, audit_log, and ALL storage policies) inherit the new
-- semantics for free.

create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  -- DEPRECATED under multi-profile. Returns the oldest active profile's role
  -- arbitrarily. Application code uses getAuthContext().activeProfile.role
  -- via the active_profile_id cookie. Policies that need role-specific gating
  -- now call is_branch_master_or_admin() / is_branch_chairman() instead.
  select role from public.profiles
   where user_id = auth.uid() and is_active = true
   order by created_at asc
   limit 1
$$;

create or replace function public.current_branch_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  -- DEPRECATED under multi-profile (same reasoning as current_role).
  select branch_id from public.profiles
   where user_id = auth.uid() and is_active = true
   order by created_at asc
   limit 1
$$;

create or replace function public.is_taylab_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
     where user_id = auth.uid()
       and role = 'taylab_staff'
       and is_active = true
  )
$$;

create or replace function public.is_branch_user(target_branch uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  -- "Any active role at this branch" — includes wing roles too, because
  -- wings ARE branches (branch_type='wing'). Storage policies need wings
  -- to count as branch users for events/leads-adjacent storage.
  select exists (
    select 1 from public.profiles
     where user_id = auth.uid()
       and is_active = true
       and branch_id = target_branch
       and role in (
         'branch_master_admin',
         'branch_admin',
         'branch_team_member',
         'branch_chairman',
         'wing_admin',
         'wing_chairman'
       )
  )
$$;

create or replace function public.is_branch_admin_team(target_branch uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
     where user_id = auth.uid()
       and is_active = true
       and branch_id = target_branch
       and role in (
         'branch_master_admin',
         'branch_admin',
         'branch_team_member'
       )
  )
$$;

-- New: replaces "is_branch_user(b) AND current_role() IN ('master','admin')"
-- in policies that gated by master/admin specifically.
create or replace function public.is_branch_master_or_admin(target_branch uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
     where user_id = auth.uid()
       and is_active = true
       and branch_id = target_branch
       and role in ('branch_master_admin', 'branch_admin')
  )
$$;

-- New: replaces "is_branch_user(b) AND current_role() = 'branch_chairman'".
create or replace function public.is_branch_chairman(target_branch uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
     where user_id = auth.uid()
       and is_active = true
       and branch_id = target_branch
       and role = 'branch_chairman'
  )
$$;

-- -------------------------------------------------------------------------
-- 3) Rewrite policies that called current_role() directly
-- -------------------------------------------------------------------------

drop policy if exists branches_update on public.branches;
create policy branches_update on public.branches
  for update using (
    public.is_taylab_staff()
    or public.is_branch_master_or_admin(id)
  )
  with check (
    public.is_taylab_staff()
    or public.is_branch_master_or_admin(id)
  );

drop policy if exists profiles_insert_branch_master_admin on public.profiles;
create policy profiles_insert_branch_master_admin on public.profiles
  for insert with check (
    branch_id is not null
    and public.is_branch_master_or_admin(branch_id)
  );

drop policy if exists profiles_update_branch_master_admin on public.profiles;
create policy profiles_update_branch_master_admin on public.profiles
  for update using (
    branch_id is not null
    and public.is_branch_master_or_admin(branch_id)
  );

drop policy if exists applications_update_branch_admin on public.applications;
create policy applications_update_branch_admin on public.applications
  for update using (
    public.is_taylab_staff()
    or public.is_branch_admin_team(branch_id)
    or public.is_branch_chairman(branch_id)
  );

-- -------------------------------------------------------------------------
-- 4) Rewrite profiles_select_self + profiles_update_self
-- -------------------------------------------------------------------------
-- Under multi-profile, "self" means "all rows where user_id = my auth id"
-- — a user can see/update any of their own profile rows.

drop policy if exists profiles_select_self on public.profiles;
create policy profiles_select_self on public.profiles
  for select using (user_id = auth.uid());

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
  for update using (user_id = auth.uid())
  with check (
    user_id = auth.uid()
    -- Self-update cannot change role. Reads the original row's role to
    -- compare against the new value.
    and role = (select role from public.profiles p2 where p2.id = profiles.id)
  );

-- -------------------------------------------------------------------------
-- 5) Rewrite events policies — replace inline p.id = auth.uid()
-- -------------------------------------------------------------------------

drop policy if exists "events: wing team + taylab read" on public.events;
create policy "events: wing team + taylab read"
  on public.events for select
  using (
    exists (
      select 1 from public.profiles p
      where p.user_id = auth.uid()
        and p.is_active = true
        and (
          (p.branch_id = events.branch_id and p.role in ('wing_admin', 'wing_chairman'))
          or p.role = 'taylab_staff'
        )
    )
  );

drop policy if exists "events: wing admin + taylab insert" on public.events;
create policy "events: wing admin + taylab insert"
  on public.events for insert
  with check (
    exists (
      select 1 from public.profiles p
      where p.user_id = auth.uid()
        and p.is_active = true
        and (
          (p.branch_id = events.branch_id and p.role = 'wing_admin')
          or p.role = 'taylab_staff'
        )
    )
  );

drop policy if exists "events: wing admin + taylab update" on public.events;
create policy "events: wing admin + taylab update"
  on public.events for update
  using (
    exists (
      select 1 from public.profiles p
      where p.user_id = auth.uid()
        and p.is_active = true
        and (
          (p.branch_id = events.branch_id and p.role = 'wing_admin')
          or p.role = 'taylab_staff'
        )
    )
  );

drop policy if exists "events: wing admin + taylab delete" on public.events;
create policy "events: wing admin + taylab delete"
  on public.events for delete
  using (
    exists (
      select 1 from public.profiles p
      where p.user_id = auth.uid()
        and p.is_active = true
        and (
          (p.branch_id = events.branch_id and p.role = 'wing_admin')
          or p.role = 'taylab_staff'
        )
    )
  );

-- -------------------------------------------------------------------------
-- 6) Rewrite leads policies — replace inline p.id = auth.uid()
-- -------------------------------------------------------------------------

drop policy if exists "leads: wing team + routed branch + taylab read" on public.leads;
create policy "leads: wing team + routed branch + taylab read"
  on public.leads for select
  using (
    exists (
      select 1 from public.profiles p
      where p.user_id = auth.uid()
        and p.is_active = true
        and (
          (p.branch_id = leads.wing_branch_id and p.role in ('wing_admin', 'wing_chairman'))
          or (leads.routed_to_branch_id is not null
              and p.branch_id = leads.routed_to_branch_id
              and p.role in ('branch_master_admin', 'branch_admin', 'branch_team_member', 'branch_chairman'))
          or p.role = 'taylab_staff'
        )
    )
  );

drop policy if exists "leads: wing admin + taylab insert" on public.leads;
create policy "leads: wing admin + taylab insert"
  on public.leads for insert
  with check (
    exists (
      select 1 from public.profiles p
      where p.user_id = auth.uid()
        and p.is_active = true
        and (
          (p.branch_id = leads.wing_branch_id and p.role = 'wing_admin')
          or p.role = 'taylab_staff'
        )
    )
  );

drop policy if exists "leads: wing admin + routed branch admin + taylab update" on public.leads;
create policy "leads: wing admin + routed branch admin + taylab update"
  on public.leads for update
  using (
    exists (
      select 1 from public.profiles p
      where p.user_id = auth.uid()
        and p.is_active = true
        and (
          (p.branch_id = leads.wing_branch_id and p.role = 'wing_admin')
          or (leads.routed_to_branch_id is not null
              and p.branch_id = leads.routed_to_branch_id
              and p.role in ('branch_master_admin', 'branch_admin', 'branch_team_member'))
          or p.role = 'taylab_staff'
        )
    )
  );

drop policy if exists "leads: taylab delete" on public.leads;
create policy "leads: taylab delete"
  on public.leads for delete
  using (
    exists (
      select 1 from public.profiles p
      where p.user_id = auth.uid()
        and p.is_active = true
        and p.role = 'taylab_staff'
    )
  );

-- -------------------------------------------------------------------------
-- 7) Documentation
-- -------------------------------------------------------------------------

comment on column public.profiles.id is
  'Profile identity. Independent UUID (default gen_random_uuid). Was FK to auth.users.id pre-2026-05-17.';

comment on column public.profiles.user_id is
  'Auth user FK. Many profiles per user (multi-profile model added 2026-05-17). Active profile selected at app layer via active_profile_id cookie.';

comment on function public.current_role() is
  'DEPRECATED under multi-profile. Returns the oldest profile arbitrarily. Application code uses getAuthContext().activeProfile.role instead.';

comment on function public.current_branch_id() is
  'DEPRECATED under multi-profile. Same reasoning as current_role().';
